import {
  createAsyncThunk,
  createEntityAdapter,
  createSlice,
  nanoid,
} from '@reduxjs/toolkit';
import axios from 'axios';

import { POLICYHOLDERS_API } from '../../../constants/apiLinks';
import { Policyholder, PolicyHoldersState } from './interfaces';

const initialState: PolicyHoldersState = {
  status: 'idle',
};

export const policyholdersAdapter = createEntityAdapter<Policyholder>({
  selectId: () => nanoid(),
});

export const getPolicyholders = createAsyncThunk(
  'policyholders/fetchInfo',
  async () => {
    const response = await axios.get(`${POLICYHOLDERS_API}/policyholders`);
    return response.data.policyHolders;
  }
);

export const policyholdersSlice = createSlice({
  name: 'policyholders',
  initialState: policyholdersAdapter.getInitialState(initialState),
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder.addCase(getPolicyholders.fulfilled, (state, action) => {
      state.status = 'idle';

      if (action.payload) {
        policyholdersAdapter.setAll(state, action.payload);
      }
    });
  },
});

export default policyholdersSlice.reducer;
